django_project/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login")
]

django_project/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [   
    path('', views.article_list, name="list"),
    path('<slug:slug>/', views.article_detail, name="detail"),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path('', views.homepage ),
    path('about/', views.about),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('home/', views.homepage ),
]

django_project/accounts/models.py
from django.db import models

# Create your models here.

django_project/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField() 
    body = models.TextField() 
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", blank=True)
    #add in author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+"..."

django_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


def signup_view(request):
     if request.method == "POST":
         form = UserCreationForm(request.POST)
         if form.is_valid():
             form.save()
             # log the user in
         return redirect('articles:list')
     else:
         form = UserCreationForm()
     return render(request, "accounts/signup.html", {"form": form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form":form})

django_project/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(request, "articles/article_list.html", {"articles":articles})

def article_detail(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, "articles/article_detail.html", {"article": article})

django_project/django_project/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, "homepage.html")


def about(request):
    return render(request, "about.html")

django_project/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<div>
    <h1>Login</h1>
    <form class="site-form" action="/accounts/login/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

django_project/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<div>
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
</div>

{% endblock %}

django_project/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %} {% block content %}

<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumb.url }}" alt="">
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
  </div>
</div>

{% endblock %}

django_project/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="articles">
      <h1>Articles</h1>
      {% for article in articles %}
      <div class="article">
    <!--     <h2><a href="{{ article.slug }}"><li>{{ article.title }}</li></a></h2> -->
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
      </div>
      {% endfor %}
    </div>
{% endblock %}

django_project/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="about">
    <h1>This is the About page</h1>
    <p>Some info</p>
</div>
{% endblock %}

django_project/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tactical Games</title>
    <link rel="stylesheet" href="../static/assets/styles.css">
  </head>
  <div class="wrapper">
    <h1><a href="{% url 'articles:list' %}"><img src="{% static '../static/assets/megaman.jpeg' %}" alt="articles link" /></a></h1>

   
    {% block content %}
    {% endblock %}
  </div>
</html>

django_project/templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="homepage">
    <h1>This is the homepage</h1>
    <p>Welcome to the website</p>
</div>
{% endblock %}